spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 1230
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.aloneness.springbootmybatis.domain
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql